---
abstract: 'Find the Roots of Polynomial Equations'
author:
  - 'John M. Gamble <jgamble@cpan.org>'
build_requires:
  Test::Simple: 0
configure_requires:
  Module::Build: 0.3624
generated_by: 'Module::Build version 0.3624'
keyword:
  - math
  - polynomial
  - quadratic
  - cubic
  - quartic
  - matrix
  - Sturm
  - Nickalls
  - Ferrari
  - Laguerre
  - Hessenberg
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Polynomial-Solve
provides:
  Math::Polynomial::Solve:
    file: lib/Math/Polynomial/Solve.pm
    version: 2.62_1
requires:
  Math::Complex: 1.36
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/jgamble/Math-Polynomial-Solve.git
    web: https://github.com/jgamble/Math-Polynomial-Solve
version: 2.62_1
